# Generated by Django 4.2.3 on 2023-08-01 15:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import pharmashop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('publier', 'Peut publier catégorie'),),
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('pays', models.CharField(default='', max_length=255)),
                ('ville', models.CharField(default='', max_length=255)),
                ('telephone', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantTotal', models.IntegerField(default=1)),
                ('quantiteTotal', models.IntegerField(default=1)),
                ('reduction', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='pharmashop.entrepot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prix', models.PositiveBigIntegerField(default=1)),
                ('marque', models.CharField(blank=True, default='', max_length=255)),
                ('date_exp', models.DateTimeField(blank=True, default='2042-06-10T17:07:03.121812Z', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=pharmashop.models.upload_path)),
                ('masse', models.CharField(default='', max_length=10)),
                ('qte_stock', models.PositiveBigIntegerField(default=1)),
                ('stockAlert', models.PositiveBigIntegerField(default=1)),
                ('stockOptimal', models.PositiveBigIntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('posologie', models.TextField(default='')),
                ('voix', models.IntegerField(choices=[(0, 'bucale'), (1, 'injection'), (2, 'anale')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.categorie')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.entrepot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MouvementInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adresse', models.CharField(default='ras', max_length=255)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('status', models.CharField(default='', max_length=255)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=10)),
                ('nom', models.CharField(default='', max_length=255)),
                ('localisation', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='patrick1kenne@gmail.com', max_length=254, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('h_ouverture', models.CharField(default='08:00 AM', max_length=15, null=True)),
                ('h_fermeture', models.CharField(default='08:00 PM', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='pharmashop.utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('quantite', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.entrepot')),
                ('medicament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MedicamentFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=1)),
                ('quantite', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.facture')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.pharmacie'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.utilisateur'),
        ),
        migrations.CreateModel(
            name='InventaireMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteAttendue', models.IntegerField(default=1)),
                ('quantiteReelle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.inventaire')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='medicaments',
            field=models.ManyToManyField(through='pharmashop.InventaireMedicament', to='pharmashop.medicament'),
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basePrix', models.CharField(default='HT', max_length=255)),
                ('tva', models.FloatField(default=19.25)),
                ('prixVente', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='pharmashop.medicament')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='medicaments',
            field=models.ManyToManyField(through='pharmashop.MedicamentFacture', to='pharmashop.medicament'),
        ),
        migrations.AddField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='pharmashop.utilisateur'),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='pharmashop.pharmacie'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maladie', models.ManyToManyField(through='pharmashop.Carnet', to='pharmashop.maladie')),
                ('symptome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.symptome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='carnet',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.consultation'),
        ),
        migrations.AddField(
            model_name='carnet',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.maladie'),
        ),
        migrations.AlterUniqueTogether(
            name='medicament',
            unique_together={('nom', 'pharmacie')},
        ),
    ]
