# Generated by Django 4.0.5 on 2022-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
