# Generated by Django 4.0.5 on 2022-07-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consultaion',
            name='maladie',
            field=models.ManyToManyField(through='pharmashop.Carnet', to='pharmashop.maladie'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.maladie'),
        ),
    ]
