# Generated by Django 4.0.5 on 2022-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='pharmacie',
        ),
        migrations.AddField(
            model_name='medicament',
            name='voix',
            field=models.IntegerField(choices=[(0, 'Enfant'), (1, 'Adolescent'), (2, 'Adulte'), (3, 'Tous')], default=3, max_length=1),
        ),
    ]
