# Generated by Django 4.0.5 on 2022-06-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0002_alter_pharmacie_latitude_alter_pharmacie_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.pharmacie'),
        ),
    ]
