# Generated by Django 4.0.5 on 2022-08-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0002_alter_medicament_prix_alter_medicament_qte_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='pharmashop.pharmacie')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantTotal', models.IntegerField(default=1)),
                ('quantiteTotal', models.IntegerField(default=1)),
                ('reduction', models.IntegerField(default=0)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='pharmashop.entrepot')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.RenameModel(
            old_name='Consultaion',
            new_name='Consultation',
        ),
        migrations.AddField(
            model_name='medicament',
            name='stockAlert',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicament',
            name='stockOptimal',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MedicamentFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=1)),
                ('quantite', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.facture')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='InventaireMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteAttendue', models.IntegerField(default=1)),
                ('quantiteReelle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.inventaire')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='medicament',
            field=models.ManyToManyField(through='pharmashop.InventaireMedicament', to='pharmashop.medicament'),
        ),
        migrations.AddField(
            model_name='facture',
            name='medicament',
            field=models.ManyToManyField(through='pharmashop.MedicamentFacture', to='pharmashop.medicament'),
        ),
        migrations.AddField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='pharmashop.utilisateur'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.entrepot'),
        ),
    ]
