# Generated by Django 4.0.5 on 2022-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0003_entrepot_facture_inventaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepot',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventaire',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='medicament',
            new_name='medicaments',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='posologie',
            field=models.TextField(),
        ),
    ]
