# Generated by Django 4.0.5 on 2022-06-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0003_alter_medicament_pharmacie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptome',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='carnet',
            old_name='reponse',
            new_name='message',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='experience',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.consultaion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
