# Generated by Django 4.0.5 on 2022-08-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0004_alter_entrepot_options_alter_inventaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='entrepot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.entrepot'),
            preserve_default=False,
        ),
    ]
