# Generated by Django 4.0.5 on 2022-08-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0005_alter_medicament_entrepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='inventaire',
            old_name='medicament',
            new_name='medicaments',
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='pays',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='telephone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='ville',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='libelle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_exp',
            field=models.DateTimeField(default='2042-06-10T17:07:03.121812Z'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='marque',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='masse',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='posologie',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmashop.utilisateur'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('quantite', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.entrepot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
