# Generated by Django 4.0.5 on 2022-08-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0007_alter_medicament_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentfacture',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basePrix', models.CharField(default='HT', max_length=255)),
                ('tva', models.FloatField(default=19.25)),
                ('prixVente', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='pharmashop.medicament')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmashop.utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
