# Generated by Django 4.0.5 on 2022-08-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0008_alter_medicamentfacture_options_historiqueprix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'permissions': (('publier', 'Peut publier catégorie'),)},
        ),
    ]
