# Generated by Django 4.0.5 on 2022-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0009_alter_categorie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='h_fermeture',
            field=models.CharField(default='08:00 PM', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='h_ouverture',
            field=models.CharField(default='08:00 AM', max_length=15, null=True),
        ),
    ]
