# Generated by Django 4.0.5 on 2022-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0010_alter_pharmacie_h_fermeture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='email',
            field=models.EmailField(blank=True, default='patrick1kenne@gmail.com', max_length=254, null=True),
        ),
    ]
