# Generated by Django 4.0.5 on 2022-09-06 00:13

from django.db import migrations, models
import django.db.models.deletion
import pharmashop.models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0011_pharmacie_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='medicament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmashop.medicament'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_exp',
            field=models.DateTimeField(blank=True, default='2042-06-10T17:07:03.121812Z', null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.FileField(upload_to=pharmashop.models.upload_path),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='marque',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
