# Generated by Django 4.0.5 on 2022-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0012_mouvementstock_medicament_alter_medicament_date_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='qte_stock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
