# Generated by Django 4.0.5 on 2022-09-17 14:36

from django.db import migrations, models
import pharmashop.models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmashop', '0013_alter_medicament_qte_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reduction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=pharmashop.models.upload_path),
        ),
    ]
